general:
  config_reload_commands: []
  focus_follows_cursor: true
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: 'monitor_focus'
  hide_method: 'cloak'
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  inner_gap: '8px'
  outer_gap:
    top: '8px'
    right: '8px'
    bottom: '8px'
    left: '8px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#2F2F2F'
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: 'small_rounded'
  other_windows:
    border:
      enabled: true
      color: '#4E4E4E'
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: 'small_rounded'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: true
      shown_on_top: false

workspaces:
  - name: '1'
    bind_to_monitor: 1
  - name: '2'
    bind_to_monitor: 1
  - name: '3'
    bind_to_monitor: 1
  - name: '4'
    bind_to_monitor: 1
  - name: '5'
    bind_to_monitor: 1
  - name: '6'
    bind_to_monitor: 1
  - name: '7'
    bind_to_monitor: 1
  - name: '8'
    bind_to_monitor: 1
  - name: '9'
    bind_to_monitor: 2
    
window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { regex: "zebar|League of Legends|VALORANT|r5apex|r5apex_dx12|cs2|RustClient|helldivers2" }
  - commands: ["move --workspace 8"]
    match:
      - window_process: { regex: "WindowsTerminal" }

binding_modes:
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:

  # programs
  - commands: ['shell-exec %ProgramFiles%\Alacritty\alacritty.exe']
    bindings: ['alt+enter']
  - commands: ['shell-exec alacritty --command "C:\Program Files\PowerShell\7\pwsh.exe"']
    bindings: ['alt+shift+enter']
  - commands: ['shell-exec alacritty --command "powershell.exe C:\Users\hatosu\files\os\windows\scripts\find.ps1"']
    bindings: ['alt+s']

  # glazewm
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']
  - commands: ['resize --width -2%']
    bindings: ['alt+p']
  - commands: ['resize --width +2%']
    bindings: ['alt+u']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']
  - commands: ['wm-toggle-pause']
    bindings: ['alt+shift+d']
  - commands: ['toggle-floating --centered']
    bindings: ['alt+x']
  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']
  - commands: ['close']
    bindings: ['alt+q']
  - commands: ['wm-exit']
    bindings: ['alt+shift+y']
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']
